### ISSUE TITLE
Change multiple attributes at once - audio /image trimming, colour space conversion etc

### ISSUE THREAD

**Issue by Colm-Connolly** [cth103/dcpomatic#7]
Hi,

We are using OSX El Capitan with DCP-O-Matic version 2.14.11 (i know we should upgrade, but the changelog doesn't look like this has been fixed).

We noticed that we can select multiple source images (DCDM TIFFS in our case) and set the scaling for all sources at once. When selecting things like colour space conversion though, it only seems to allow for change the setting for one of the sources, not all.

Same goes for audio - let' say you have 30 audio inputs and you want to trim 8 seconds of audio from the head and tail, you have to do it for each one manually.
I'd imagine that all off this is because they have to set manually - audio has the 'set' button, and the colour space has the 'edit' for manual adjustments. It would be great to be able to make batch changes though.

**Comment by cth103** [comment]
Hi Colm,

The timing adjustment of multiple things should already be possible, but there's a bug for which I'll put a fix into 2.14.31.

The colour space conversion is a bit more tricky, just from a UI perspective.  If we select two video sources with different colour spaces we need some way for the drop-down box to say "multiple selected" so that the user knows what's going on.  I'll try out some ideas for that.

**Comment by cth103** [comment]
OK, that wasn't so hard; this should all be fixed in 2.14.31 if you'd like to try it out.  It might be a few days before it's uploaded.

**Comment by kieranjol** [comment]
Amazing, thank you so much for this fix, can't wait to try it out!
